openep/openep-py

requirements.txt
tests/main.py

Didn't think much of matplotlib, so added VTK visualisation. 
@ericspod i know you're not a fan of VTK, but thought I'd just knock together a quick example as it's pretty straightforward.

start to add vtk visualisation

---

examples/main.py
openep/view/view_pyqt_vtk.py
requirements.txt

Embedded VTK visualisation, see video for example.
https://user-images.githubusercontent.com/33289025/122245848-fd600000-cebd-11eb-8fa1-e678a2a8bb33.mov

embedded vtk visualisation

---

openep/view/view_gui.py

Changes made:
* #96 broke the ability to load MATLAB files in the GUI - it's fixed here.

Fix ability to load mat files in the GUI

---

openep/view/canvases.py
openep/view/custom_widgets.py
openep/view/system_manager.py
openep/view/system_manager_ui.py
openep/view/view_gui.py

Fix formatting to resolve flake 8 complaints

Fix formatting

---

openep/case/case_routines.py
openep/data_structures/ablation.py
openep/data_structures/case.py
openep/data_structures/surface.py
openep/io/readers.py
openep/io/writers.py
openep/view/plotters_ui.py
openep/view/system_manager.py
openep/view/system_manager_ui.py
openep/view/system_ui.py
openep/view/view_gui.py

Changes made:
* Mapping points plotted as spheres now correctly scale when the size of the window changes.
* This is done using glyphs rather than directly adding points to the plot.
* Fixed Flake 8 complaints

Scale 3D spheres points when resizing the GUI

---

openep/view/plotters.py

Changes made:
* Use parallel projection (rather than orthoscopic) for the cameras in the 3d viewers of the GUI

Parallel projection

---

openep/view/view_gui.py

Changes made:
* Allow moving to the previous or next row in the mapping points or recycle bin table from the annotaiton viewer. This changes the electrogram that is displayed in the annotation viewer, and also highlights the new point in the 3d viewer of the active system.
* Use the up and down arrows to move between mapping points.
* Up arrow moves to the previous point, down arrow to the next.
* If the current-selected point has been deleted, the recycle bin table will be traversed, otherwise the mapping points table will be used.

Move to next/previous mapping point from the annotation viewer

---

examples/openep_caseroutines.py
openep/_datasets/openep_datasets.py
openep/data_structures/ablation.py
openep/data_structures/electric.py
openep/data_structures/surface.py
openep/io/readers.py
openep/io/writers.py
tests/test_case_routines.py

Changes made:
* Explicity set dtype of all numpy arrays when loading files.
* Otherwise some arrays loaded by scipy from mat files are incorrect, i.e. either str or uint8 when they should be float (np.int64)

Fix using scipy to load mat files of version 7 and below

---

openep/data_structures/case.py

Changes made:
* Add ref egms and ecgs (all set to 0 everywhere) when loading unipolar egms into an openCARP data set
* This is so that the traces can be plotted in the annotation viewer of the gui

Add zero-valued ref egms and ecgs when loading unipolar egms into an openCARP data set

---

openep/draw/draw_routines.py

Changes made:
* add missing commit from previous PR (#155)

 Internal naming of free boundaries when adding mesh to plotter

---

openep/data_structures/surface.py

Changes made:
* Correctly set missing fields to be None when loading an openep dataset

Fix for pr #184

---

openep/mesh/mesh_routines.py

Changes made:
* Use [`ij` indexing](https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html) when creating a meshgrid
* This simplifies the creation of the voxel grid

Use ij indexing when voxelising a mesh

---

.readthedocs.yaml

Changes made:
* new `readthedocs.yaml` - use python3.9 to build docs

Update rtd yaml

---

openep/mesh/mesh_routines.py

Changes made:
* Added a new class `openep.mesh.mesh_routines.Boundary`
* Base class for `openep.mesh.mesh_routines.FreeBoundary`
* Not used in `openep` per se, but will be used by the gui application

Add new openep.mesh.Boundary class

---

openep/io/writers.py

Changes made:
* Set correct header in .pts file when exporting to opencarp format. Should specify N points, previously wrote N points * 3

Fix export to opencarp

---

openep/data_structures/surface.py

Changes made:
* remove import of `syslog` - it's not needed and breaks import on windows

Remove unused imports

---

examples/check-landmark-points.py
openep/data_structures/case.py
openep/data_structures/electric.py
openep/data_structures/surface.py
openep/io/matlab.py
openep/io/writers.py
tests/test_writers.py

Changes made:
* Calculate nearest point and normals after adding a landmark
* Fix import/export of cases that have had landmarks added

Fix add_landmark method

---

openep/converters/pyvista_converters.py
openep/data_structures/case.py
openep/data_structures/electric.py
openep/io/writers.py

Changes made:
* Fix creating a case from a pyvista mesh
* Fix exporting openep mat file when annotations are missing
* Fix adding unipolar egms to an openCARP case

Fix imports and exports

---

openep/data_structures/electric.py

Changes made:
* Fix `egm.n_points` and `egm.n_samples` for when there are landmark points but no mapping points

Fix egm.n_points and egm.n_samples

---

openep/data_structures/case.py

Changes made:
* Add `case.transform` methods that takes a transformaiton matrix and applies it to all 3d coordinates in a case

Add method to apply a transformation to the coordinates in a case
