openep/__init__.py, openep/data_structures/openCARP.py, openep/io/readers.py, openep/view/view_gui.py
Changes made:
* add a `openep.io.readers.load_openCARP` function (callable as `openep.load_openCARP`). This currently requires:
* a points file (for 3d coordinates)
* an elements file (for definition of each triangle in the mesh)
* a data file (.dat, for the unipolar electrograms associated with each point).
* `load_openCARP` creates a `CARPData` object. Creation of this object automatically calculates the bipolar electrograms and voltages from the unipolar electrograms. 
* `CARPData` has a `create_mesh` function, which will create a `pyvista.PolyData` mesh. This mesh can be passed to `openep.draw.draw_map` for visualisation.
* openCARP files can be loaded in the GUI, but currently nothing happens when the files are loaded. It would be best to refactor the GUI first as described in #88 …
=> Add basic support for reading and visualising openCARP

openep/view/view_gui.py
Fix the regex for egm selection so that numbers are extracted rather than digits. i.e. previously a selection of `100` would plot three egms - the one at index 1 as well as the one at index 0 twice
=> Fix egm selection

openep/draw/draw_routines.py, openep/view/system_manager.py, openep/view/view_gui.py
Fixes #95 
Add a `QDoubleSpinBox` for setting the opacity of a single mesh. Takes values between 0 a 1, with in increments of 0.05. The map is redrawn after each change in opacity value.
=> Add ability to change opacity of the mesh

openep/view/view_gui.py
Changes made:
* when changing the colourbar limits, the scalar range of the mapper is changed rather than redrawing the whole scene
* when changing the opacity of the mesh, the opacity of the actor is changed in place rather than redrawing the scene each time
TODO: when changing the field projected onto the mesh, use pyvista's `set_active_scalars` rather than redrawing the scene
=> Streamline changes to renderer

openep/view/system_manager.py, openep/view/view_gui.py
Fixes #2 
Changes made:
* `openep.draw.draw_map` has previously been modified to use any provided scalar field. In this PR, the option to use the following scalar fields in the GUI has been added:
- Bipolar voltage (interpolated for OpenEP datasets, calculated from EGMs for openCARP)
- Unipolar voltage (as above)
- Clinical bipolar voltage
- Clinical unipolar voltage
- Clinical LAT
- Clinical force
- Clinical impedance
* For the clinical fields, the options are only available if the field is not full of NaNs
* Pyvista's `mesh.set_active_scalars` is used to control which field is currently used. There is a bug in pyvista that changes the active scalars if a title is set for the colourbar (see https://github.com/pyvista/pyvista/issues/1900#issue-1067446986). This is handled by checking the …
=> Add scalar fields

openep/__init__.py, openep/io/__init__.py, openep/io/writers.py
Changes made:
* Added a funciton `openep.io.writers.export_openCARP` writes OpenEP mesh data into openCARP format
* Currently only writes points (*.pts) and triangle (*.elem) data
=> Initial support for exporting data in openCARP format

openep/data_structures/openCARP.py, openep/view/view_gui.py
Changes made:
* Add an Export option to the File menu of the GUI for exporting OpenEP datasets
* Currently, can only be used to export mesh data from an OpenEP case into openCARP format (*.pts and *.elem files).
* Uses `openep.io.writeres.export_openCARP`
=> Add option to GUI to to export OpenEP data to openCARP

openep/view/view_gui.py
Changes made:
* The title of each window is determined from the user-set name of the system and the user-selected field that is projected onto the mesh
=> Ensure dock window title is set correctly in the GUI

openep/data_structures/case.py, openep/view/system_manager.py, openep/view/system_ui.py, openep/view/view_gui.py
Fixes #92 
Changes made:
* Added a 'Show/Hide' menu to the menubar of each 3d viewer
* Can selected to show or hide the:
* mesh
* mapping points
* surface-projected mapping points
* By default, only the mesh is visible
* The opacity selector changes the opacity of the mesh only (not that of the mapping points)
* The Field selection is used to colour the mesh only (all points are rendered grey).
=> Visualise mapping points in the GUI

openep/data_structures/case.py
Update to #113 
Changes made:
* Ensure the show/hide menu of the 3d viewers works for opencarp cases
* Previously, there were no surface projected points calculated when loading an opencarp case and unipolar electrograms
=> Visualise mapping points in the GUI - opencarp

requirements.txt
Changes made:
* PyQt5 version must be less than 5.14.
* With versions >=5.14 the screen flickers red when resizing the 3d viewers.
=> Set maximum PyQt5 version

openep/view/plotters.py
Changes made:
* In the GUI, the `BackgroundPlotter`s are set to auto-update 100 times per second (rather than the previous default of 5)
* This provides a smoother experience when rotating linked 3d viewers
* The value could be increased further, but it will start to affect performance, especially when multiple 3d viewers are openep
=> Refresh the 3d viewer more frequently

openep/view/mapping_points.py, openep/view/system_manager_ui.py, openep/view/view_gui.py
Changes made:
* Display table of mapping points in a window titled 'Mapping points'.
* Table contains:
- point index (0 based)
- point tag (internal name used by clinical mapping system)
- point name
- bipolar voltage
- local activation time
* Can sort by each column
* Can select which columns to show/hide (a context menu appears when right-clicking on the table header)
* Can delete points. Use the left mouse button to highlight points, then right-click to bring up context menu. Select 'delete point(s)'
* The points are moved to the 'Recycle bin'. This is another table, similar to the Mapping Points table, that contains the deleted points. Points can be restored from the recycle bin in the same way they are deleted from the Mapping Points table.
=> Add table to the GUI for displaying info about mapping points

openep/data_structures/case.py, openep/data_structures/electric.py, openep/view/annotations_ui.py, openep/view/mapping_points.py, openep/view/system_manager.py, openep/view/view_gui.py
Changes made:
* There is no longer a QComboBox for selecting which electrogram to plot in the annotation viewer
* Instead, the electrogram to plot is determined by the currently-selected point in the mapping points and recycle bin tables
* The name of the point is displayed where the QComboBox was, using a QLabel
* If the point has been deleted (i.e. moved to the recycle bin), this is indicated in the QLabel
=> Plot the electrogram of the currently selected point

openep/view/annotations_ui.py, openep/view/view_gui.py
Changes made:
* Fixed the updating of artists in the annotation viewer. #122 introduced a bug in which the annotation viewer hadn't been updated to account for the removal of the QComboBox. 
* Can no longer press the 'Up' or 'Down' keys in the annotation viewer to change which mapping is has its electrograms displayed. The mapping point must be selected in the tables (mapping points or recycle bin).
=> Use correct mapping point index when adjusting annotations in the GUI

openep/view/mapping_points.py, openep/view/system_manager.py, openep/view/view_gui.py
Changes made:
* enable point picking in the primary 3d viewer of the active system
* press 'p' to select one of the mapping points ( must be a mapping point - not a surface-projected mapping point)
* this will draw that mapping point as a large red sphere
* it will also select the mapping point in the relevant table (mapping points table or recycle bin), and plot the electrogram for this point
* selecting a point in the mapping points or recycle bin tables will highlight this point in the 3d viewer
=> Enable point picking in the 3d viewer

openep/view/view_gui.py
Changes made:
* Make the bounding box white (rather than the default bright red) when picking points in the 3d viewer of the GUI
=> Bounding box when picking points in the GUI

openep/view/view_gui.py
Changes made:
* In the GUI, when changing the active system, ensure the correct annotations are set in the annotation viewer
=> Set correct annotation in the GUI

openep/view/plotters.py
PyVista's `BacgroundPlotter` subclasses `QVTKRenderWindowInteractor`. The point picker of the interactor unnecessarily and incorrectly scales the coordinates of picked points. See: 
* https://gitlab.kitware.com/vtk/vtk/-/issues/18195
* https://gitlab.kitware.com/vtk/vtk/-/merge_requests/4201/diffs
Changes made:
* After creating a `pyvista.BackgroundPlotter`, set the `_getPixelRatio` static method of it's interactor to always return 1. This prevents the scaling of the coordinates of the picked point.
=> Ensure point-picking works on Mac retina displays

openep/view/view_gui.py
Changes made:
* when deleting a point from the mapping points table, re-select the point in the recycle bin. This means the same electrograms will be displayed in the annotation viewer, but the label of the displayed point will update to indicate the point is deleted
* likewise when restoring points from the recycle bin
* when using the up/down keys in the annotation viewer to move to the next/previous point, is the point has not been deleted then ensure only rows visible in the mapping points table are traversed. If the mapping point has been deleted, then ensure only rows visible in the recycle bin are traversed when using the up/down keys
=> Update selected point when deleting or restoring points in the GUI

openep/__init__.py, openep/io/readers.py, openep/io/writers.py, openep/view/system_manager_ui.py, openep/view/view_gui.py, tests/test_writers.py
Fixes #133 
Changes made:
* added a function `openep.io.writers.export_openep_mat` to store data in the OpenEP MATLAB format
* currently, the following fields are exported:
- `userdata.notes`
- `userdata.surface`
- `userdata.electric` (`userdata.electric.impedances` are currently transposed compared to in OpenEP-core)
- `userdata.surface`
- `userdata.rf`
*  `userdata.surface.isVertexAtRim` and `userdata.rf_index` cannot be exported as they are not yet read in by `openep.load_openep_mat`
* Account for the 1-based indexing in MATLAB (and so `userdata.surface.triRep.Triangulation` indices are different)
* Added a simple test for writing OpenEP mat files. It checks whether the scalar fields (bipolar voltage, LAT, etc.) are the same in the original data set and in a data set written using …
=> Export data in OpenEP format (*.mat)

openep/view/plotters.py, openep/view/system_manager.py, openep/view/view_gui.py
Fixes #136 
Changes made:
* When mapping points are deleted, they are displayed as yellow spheres in all relevant 3d viewers
* When they are restored, the colour returns to white
* It is not simple to hide the deleted points. It could be done using a separate mesh for each mapping point, but it is slow to create hundreds or thousands of meshes. The opacity of points can be set using scalar values, but points with zero opacity are still pickable, meaning points that are not visible can still be picked.
* Having two meshes - one for mapping points and one for deleted points - might work, deleting points from relevant mesh and adding them to the other when points are deleted/restored.
=> Colour deleted points yellow in 3d viewers of the GUI

openep/view/system_manager.py, openep/view/view_gui.py
Fixes #135 
Changes made:
* The surface-projected mapping points are shown as 3d cylinders
* Each cylinder is centered on the location of the projected point, and oriented along the normal to the surface at that point
* As with the mapping points that are shown as spheres, the cylinders are coloured yellow if they have been deleted and white otherwise
=> Show projected mapping points as cylinders in 3d viewers of the GUI

openep/view/system_manager.py, openep/view/view_gui.py
Fixes #142 
Changes made:
* The selected projected point is rendered as a large blue cylinder in the primary viewer of the active system
* It is not shown if projected points are turned off in the show/hide menu
=> Highlight selected projected point

openep/view/preferences.py, openep/view/preferences_ui.py, openep/view/view_gui.py
Changes made:
* By default, when settings are loaded by `QSettings`, all values are of type `str`. Ensure the correct types of preference values are set at start-up
=> Ensure correct types of preferences at start up

openep/view/preferences.py, openep/view/preferences_ui.py, openep/view/view_gui.py
Fixes #147 
Changes made:
* Get preference value form the preferences dock rather than the preferences store.
* This is necessary because on Windows all values in the store always have type str, whereas on Mac OS and Linux the values take on the correct type if the values in the store are modified. So retrieving the values from the store would need to be handled differently on different operating system.
=> Set preferences using values from widgets, not from QSettings

openep/data_structures/case.py
Changes made:
* When adding unipolar egms to an openCARP case, create default tags and names
* names are given by the index of the egm
* tags are the same as names, but prefixed with 'P'
=> Add default names and tags when loading an opencarp file

openep/case/case_routines.py
Changes made:
* Store the correct indices of pairs of unipolar egms that make up each bipolar egm
* Previously, the bipolar egm was calculated correctly, the pairs of unipolar egm that correspond to each bipolar egm were incorrect
=> Fix calculation of bipolar electrograms from unipolar

openep/data_structures/electric.py, openep/io/matlab.py, openep/io/readers.py
Changes made:
* Correctly decode tags for v7.3
* Handle the case where no unipolar data is present in openep datasets (for old versions of the userdata data structure) - create default egm with values of 0 everywhere
* correctly handle missing ablation data and notes when loading an openep dataset
=> Fix openep mat file parser

openep/data_structures/surface.py, openep/io/readers.py
Changes made:
* Add option to fill scalar field arrays with NaNs when loading openCARP datasets
* set the `fill_fields` of `openep.load_openCARP` to `True` (defaults to `False`)
=> Create scalar field arrays for openCARP datasets

openep/io/readers.py
openCARP stores point positions in micrometres, whereas clinical mapping systems export positions in units of mm. 
Changes made:
* Add option to `openep.load_openCARP` to scale 3D point positions
* Use the keyword `scale_points`, which is a float value that defaults to 1
* This can be used to convert units from micrometre to mm
=> Scale openCARP points data

openep/data_structures/case.py, tests/test_data_structures.py
Changes made:
* Remove the `recenter` argument from `openep.data_structures.case.Case.create_mesh`
* Add a `translate` method to `openep.data_structures.case.Case` that takes a 3D translation that will be applied to:
* `case.points`
* `case.electric.bipolar_egm.points`
* `case.electric.unipolar_egm.points`
* `case.electric.surface.nearest_point`
* Add a `center` method to `openep.data_structures.case.Case` that translates all 3D coordinates so that the center of geometry of `case.points` is at the origin
=> Translate case

openep/case/__init__.py, openep/case/case_routines.py
Changes made:
* Add a helper function to interpolate local activation times onto the surface of a mesh, `openep.case.case_routines.interpolate_activation_time_onto_surface`
* Defaults to using a RBF interpolator with the same settings as `openep.case.case_routines.interpolate_voltage_onto_surface`
=> Interpolate local activation times

openep/data_structures/electric.py, openep/io/writers.py
Fixes #161 
Changes made:
* Export the gain and `electric.include` data when saving a dataset in openep format
* When loading an openep dataset, check whether these values exist before creating default values
=> Fix saving files in openep format

openep/data_structures/case.py, openep/data_structures/electric.py, openep/io/readers.py
Changes made:
* Fix adding egms to openCARP dataset - `case.electric.internal_names` is now the same as `case.electric.names`, rather than an array of empty strings
* Fix creation of empty Field data - default size is now 0 rather than None. Using None creates a 0d array with a single value, rather than a 1d array with no values.
=> Fix writing and loading openCARP datasets

openep/io/writers.py
Changes made:
* When exporting to .mat, cast `case.indices` to be float rather than int.
* This is to be consistent with data exported from MATLAB, and because the `TriRep` MATLAB class requires faces to be doubles rather than ints.
=> When exporting to .mat, cast case.indices to be double rather than int

examples/bipolar_from_unipolar.py, examples/openep_load_cvi.py, openep/__init__.py, openep/io/_circle_cvi.py, openep/io/readers.py, requirements.txt
Changes made:
* Added a reader for Circle CVI workspace file
* Creates a pyvista.PolyData mesh from the contours defined in the workspace file along with associated dicom files
* Added an example of how to use the reader
* Optionally returns a pandas DataFrame containing metadata about the dicoms used in constructing the mesh
* Creates either the epi or endo surface mesh, or both
=> Add reader for Circle CVI workspaces

examples/openep_converters.py, openep/converters/__init__.py, openep/converters/pyvista_converters.py, openep/data_structures/case.py
Changes made:
* added new module `openep.converters`
* added function `openep.converters.pyvista_converters.from_pyvista` - to convert a `pyvista.PolyData` mesh to an `openep.Case` dataset. Note - currently, no point, cell, or field data is extracted from the mesh
* added function `openep.converters.pyvista_converters.to_pyvista`. Equivalent to `case.create_mesh` but with the added option of adding scalar fields to the created mesh as point data (stored in `mesh.point_data`)
=> Add pyvista-to-openep converter

openep/data_structures/electric.py, openep/io/matlab.py
Changes made:
* Fix reading impedances in openep datasets
* `case.electric.impedances.time` and `case.electric.impedances.value` are not lists of numpy arrays
* We cannot use a single numpy array as it is not guaranteed that each row has the some number of columns
=> Fix reading impedances in openep datasets

openep/case/interpolators.py, requirements.txt
Changes made:
* Use numba to speed up local smoothing interpolation
* For a small case (~800 points), time reduced from ~280ms to ~150ms
* Still slower than e.g. `scipy.interpolate.LinearNDInterpolator`
=> Improve performance of LocalSmoothingInterpolator

openep/case/case_routines.py, tests/test_case_routines.py
Fixes #160 
Changes made:
* `case.electric.include` is now used to determine which mapping points should be included when interpolating (previously points were used if their local activation time was within the window of interest)
* This has been updated for interpolating both voltages and local activation times
* Separated voltage calculation from voltage interpolation (if required, voltage calculations should be done before interpolating)
* Remove unnecessary copying of data to improve performance
* `openep.case.case_routines.calculate_voltage_from_electrograms` now calculates unipolar voltages based only on the proximal egms (assumed to be `case.electric.unipolar_egm.egm[:, :, 0]`, and the distal to be `case.electric.unipolar_egm.egm[:, :, 1]`). Relevant test updated to reflect this …
=> Use case.electric.include when interpolating

openep/io/readers.py, requirements.txt
Changes made:
* Set min scipy version to 1.8.
* In 1.8, functions for checking MATLAB file version were moved
=> Bump scipy min version required

openep/data_structures/surface.py, openep/io/writers.py
Changes made:
* Added the attribute `case.fields.thickness`
* Can be used when voxelising a surface mesh
* When loading a dataset, set to np.NaN if the field is missing
* When exporting to a .mat file, stored as `userdata.surface.thickness`
=> Add a thickness attribute

openep/data_structures/electric.py, openep/io/writers.py
Fixes #179 
Changes made:
* Added an attribute `case.electric.ecg.channel_names`. It is always an array of names, even if only a single channel is present. A default name of `ECG` is used if the single channel has no name.
* `case.electric.ecg.ecg` now takes shape `n_mapping_points x n_samples x n_channels`
* `case.electric.ecg.gain` now takes shape `n_mapping_points x n_channels`
* Added an attribute `case.electric.frequency` for storing the sample frequency (defaults to 1000 Hz)
=> Handle ecgs with multiple channels

examples/openep_caseroutines.py, openep/case/__init__.py, openep/case/case_routines.py, openep/data_structures/electric.py, tests/test_case_routines.py
Changes made:
* All annotations are stored as indices:
- `case.electric.annotations._window_of_interest_indices`
- `case.electric.annotations._local_activation_time_indices`
- `case.electric.annotations._reference_activation_time_indices`
* But are accessible as times (defined as properties in the `Annotations` class):
- `case.electric.annotations.window_of_interest`
- `case.electric.annotations.local_activation_time`
- `case.electric.annotations.reference_activation_time`
=> Store all annotations as indices

examples/bipolar_from_unipolar.py, openep/data_structures/ablation.py, openep/data_structures/case.py, openep/data_structures/electric.py, openep/data_structures/surface.py, openep/io/_circle_cvi.py, openep/io/readers.py, openep/io/writers.py, openep/load-kodex-data.py, tests/test_writers.py
Changes made:
* When loading a dataset, if it is missing any attribute it is now set to be None rather than an empty array
* When exporting a dataset in openep format, any attributes that are None are set the be empty 1D arrays (as scipy cannot write None to .mat files)
* If any field in `case.fields` is missing, set it to None. Previously the field would be populated with NaN values - one per point in the mesh. However, this makes the dataset significantly larger, especially if all fields are missing (e.g. when loading openCarp datasets)
=> Set missing attributes to None rather than empty numpy arrays

openep/case/case_routines.py
Changes made:
* The window of interest is not used in determining which mapping points to include in the interpolation. Thus the 'buffer' argument to the interpolation methods is not used and has now been removed.
=> Remove 'buffer' argument from interpolation function

openep/data_structures/surface.py, openep/io/writers.py, tests/test_writers.py
Changes made:
* If any of the `case.fields` have arrays in which all values are equal to NaN, set this field to be None
* Updated the exporting of datasets to handle cases where some fields are None
* Updated the exporting tests
=> Fix importing and exporting openep datasets

openep/data_structures/electric.py
Changes made:
* When loading an openep data, if it has no gain values for the signals, the following defaults are used:
- Bipolar - 1.0
- Unipolar - 0.0
- Reference - -4.0
- ECG - 1.0
=> Set better default gain values

.github/workflows/python-app.yml
Changes made:
* rename `master` branch to `main` in github actions workflows
=> Rename master to main

.github/workflows/python-app.yml, .readthedocs.yaml, docs/conf.py, docs/make.bat, openep/data_structures/case.py, openep/mesh/mesh_routines.py
Changes made:
* Use python 3.9 for running tests and building docs
* Swtich `FreeBoundary` and `Case` classes from attrs classes to regular classes. For some reason sphinx-build would complain about not being able to infer the types of arguments in methods belonging to these attrs classes
=> Use python 3.9 for running tests and building docs

openep/data_structures/case.py, openep/data_structures/electric.py, openep/io/writers.py
Changes made:
* Added a new class `openep.data_structures.electric.LandmarkPoints` for storing data (coordinates, tags) of landmark points (either landmark-only points or landmark points with electrical data - there's no need to distinguish.)
* Landmark-only points are removed from all other data, e.g. `case.electric.bipolar_egm.egm`, `case.electric.include` etc. contain only data for mapping points with electrical signals
* The full original data is stored in the same attribute but with a leading underscore, e.g. `case.electric.bipolar_egm._egm`, `case.electric._include`
* Properties are then used along with a flag (`case.electric._is_electrical`) to filter the points with electrical data. The flag is True is a mapping point has electrical signals and False otherwise
* Using properties …
=> Separate landmark-only points from points with electrical data

openep/data_structures/case.py, openep/data_structures/electric.py, openep/data_structures/surface.py, openep/io/readers.py, openep/io/writers.py, tests/test_writers.py
Changes made:
* correctly import/export the cell region id, as well as fibres
* add option to export only longitudinal fibres (ignoring transverse). This is controlled by the argument `export_transverse_fibres` to the function `openep.export_opencarp`
* don't remove cell data in the function `openep.case.remove_unreferenced_points`
=> Fix reading and writing opencarp files

openep/case/case_routines.py
Changes made:
* Added an argument `include` to `openep.case.interpolate_voltage_onto_surface` and `openep.case.interpolate_activation_time_onto_surface`
* Defaults to None, in which case `case.electric.include` is used
* Accepts a boolean numpy array that will be used to filter mapping points instead of `case.electric.include`
=> Custom include flags for interpolation

openep/data_structures/electric.py, openep/io/writers.py, tests/test_writers.py
Changse made:
* When instantiating `openep._data_structures.Electrogram`, voltage values are assigned to be NaN if necessary
* This is done when egms are present but voltages are not, and ensures the setter for `Electrogram.voltage` works correctly
* These NaN values are not exported when saving to file
=> Electrogram class assigns voltage to NaNs

openep/data_structures/electric.py
Changes made:
* `case.electric.landmark_points` now has a `.internal_names` attribute which stores the names assigned by the mapping system
* `case.electric.landmark_points.names` stores the user-defined tags
=> Store both tags and names of landmark points

openep/data_structures/electric.py
Changes made:
* Property was previously called `names` rather than `internal_names`. This overwrote the actual `names` property.
* Also add a `__repr__`
=> Fix internal names property of Landmarks

examples/bipolar_from_unipolar.py, examples/openep_caseroutines.py, openep/data_structures/case.py, openep/data_structures/electric.py, tests/test_writers.py
Changes made:
* Added a method `Case.add_landmark`
* This is a wrapper around a method `Electric.add_landmark`, which takes a `name`, `internal_name`, and `point` (3D coordinate) to add a landmark to the dataset
* The `name` and the `internal` name must not be empty strings
* If there is no bipolar egm data, then data a new instance of `EGM` is created with:
- the `point` passed to `add_landmark`
- `egm` set to be a single row with a single NaN value
- `names` set to be an array with a single string `' '` (with a single space, not empty)
* otherwise, `case.electric.bipolar_egm` is updated in place
* For other signals (`reference_egm`, `unipolar_egm`, `ecg`, `annotation`), data is not created if the signal is not present, but arrays are modified inplace if they are present
* …
=> Add function to create a new landmark point

openep/data_structures/case.py
Changes made:
* `case.add_landmark` now takes the arguments `name` and `internal_name` rather than `tag` and `name`, to be consistent with the usage in both `case.electric.add_landmark` and `case.electric` in general
=> Fix arguments to case.add_landmark

.github/workflows/python-app.yml, openep/case/case_routines.py, openep/data_structures/surface.py, openep/io/writers.py
Changes made:
* Add `case.fields.pacing_site` array. Equal to -1 if the point does not belong to a pacing site, otherwise equal to the index of the pacing site
Also specify the CodeCov action version as a workaround to the coverage report not being updated. As suggested here: https://github.com/codecov/codecov-action/issues/598#issuecomment-1030074427
=> Add a pacing site field to case.fields

examples/check-landmark-points.py, openep/data_structures/case.py
Changes made:
* `case.electric.unipolar_egm.names` is now of shape `(n_egms, 2)` - one name per electrode
=> Fix naming of electrodes when adding unipolar egms to an openarp case

examples/check-landmark-points.py, openep/io/writers.py
Changes made:
* If any pacing sites exist (as defined by values in `case.fields.pacing_site`) the ids of each site will be written to a `.vtx` file (one file per site)
=> Write pacing sites to .vtx file when exporting to openCARP

openep/__init__.py, openep/data_structures/surface.py, openep/io/readers.py, openep/io/writers.py
Changes made:
* Added a function `openep.io.writers.export_vtk`. Takes a `Case` and a filename as input. Write the surface data to file in vtk format. Stores any fields that are not None
* Added a function `openep.io.readers.load_vtk`. Takes a filename and name as input. Loads the vtk file using pyvista. Extracts point and cell data from the mesh to populate the `Fields` of a case. Uses a newly-added class method `openep.data_structures.surface.Fields.from_pyvista` that extracts point and cell data from a `pyvista.PolyData`
=> Add support for vtk import/export

openep/data_structures/electric.py
Changes made:
* When loading an openep dataset (.mat file), add unipolar electrode names if if unipolar egms exist but the names are missing
=> Fix loading .mat file with missing unipolar electrode names
